//VERSION=3
//ndwi, based on the default NDWI script for CDSE Sentinel-2, but with values clamped to the range -1, 1.5 to avoid outlier noise
//generated by András Zlinszky @azlinszky.bsky.social and Gemini

const colorRamp1 = [
    [0, 0xFFFFFF],
    [1, 0x008000]
];
const colorRamp2 = [
    [0, 0xFFFFFF],
    [1, 0x0000CC]
];

let viz1 = new ColorRampVisualizer(colorRamp1);
let viz2 = new ColorRampVisualizer(colorRamp2);

function setup() {
  return {
    input: ["B03", "B08", "dataMask"],
    output: [
      { id: "default", bands: 4 },
      { id: "index", bands: 1, sampleType: "FLOAT32" },
      { id: "eobrowserStats", bands: 1, sampleType: "FLOAT32" },
      { id: "dataMask", bands: 1 }
    ]
  };
}

function evaluatePixel(samples) {
  // We can drop the 1/2000 factor because the index() function 
  // automatically normalizes the calculation: (a*f - b*f)/(a*f + b*f) = (a-b)/(a+b)
  let val = index(samples.B03, samples.B08);
  
  // Enforce strict mathematical limits for NDWI to filter out atmospheric correction errors
  let isValid = (val >= -1.0 && val <= 1.5);
  
  // Output NaN for stats if the pixel is masked out OR out of bounds
  const statVal = (samples.dataMask === 1 && isValid) ? val : NaN;
  
  let imgVals = null;
  
  // Safe visualization handling
  if (!isValid) {
    // Render invalid pixels as white to avoid crashing the visualizer
    imgVals = [1, 1, 1, samples.dataMask];
  } else if (val < 0) {
    imgVals = [...viz1.process(-val), samples.dataMask];
  } else {
    imgVals = [...viz2.process(Math.sqrt(Math.sqrt(val))), samples.dataMask];
  }
  
  return {
    default: imgVals,
    index: [statVal],
    eobrowserStats: [statVal],
    dataMask: [samples.dataMask]
  };
}
